spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 752040696938-m73c0dav2e7sup2cc7lrutehu9bug6un.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile